name: Markdown Lint

on:
  push:
    paths:
      - '**/*.md'
  pull_request:
    paths:
      - '**/*.md'

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Markdown Lint
        uses: DavidAnson/markdownlint-cli2-action@v8
        with:
          globs: |
            **/*.md
            !node_modules/**
            !vendor/** 